In [162]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [163]:
df = pd.read_csv(
    "../data/outs/03282/all_pin.csv",
    engine="python",      # parser mais tolerante
    on_bad_lines="skip"   # ignora linhas inválidas
)
print(df.shape)
df.head()

(56, 60)

,input,fila,n,m,c,CMP,TEST,JZ,JNZ,JL,...,POP,XCHG,TZCNT,LZCNT,BSF,BSR,PREFETCHT0,PREFETCHT1,PREFETCHT2,PREFETCHNTA
0,PIN2,1LVBQ,100,500,499,14523,16768,23438,7061,1101,...,67146,0,0,0,0,0,0,0,0,0
1,PIN2,2LVBQ,100,500,499,15755,15818,26510,6324,1301,...,70850,0,0,0,0,0,0,0,0,0
2,PIN2,3LVBQ,100,500,499,15497,14881,25927,6308,1459,...,70031,0,0,0,0,0,0,0,0,0
3,PIN2,4LVBQ,100,500,499,19155,16881,29954,7803,1922,...,82409,0,0,0,0,0,0,0,0,0
4,PIN2,5LVBQ,100,500,499,16871,15164,27808,6788,1693,...,72998,0,0,0,0,0,0,0,0,0

In [164]:
df = df.loc[:, (df != 0).any()]

In [165]:
df_pin = df.copy()
df_pin.head()

,input,fila,n,m,c,CMP,TEST,JZ,JNZ,JL,...,SAR,DIV,MOV,MOVZX,MOVSXD,LEA,CALL_NEAR,RET_NEAR,PUSH,POP
0,PIN2,1LVBQ,100,500,499,14523,16768,23438,7061,1101,...,4662,0,832510,6486,7387,59351,100404,100223,110931,67146
1,PIN2,2LVBQ,100,500,499,15755,15818,26510,6324,1301,...,3350,190,897167,6384,5720,65173,107956,107823,119173,70850
2,PIN2,3LVBQ,100,500,499,15497,14881,25927,6308,1459,...,2941,382,911408,6278,12039,64123,107352,107259,118050,70031
3,PIN2,4LVBQ,100,500,499,19155,16881,29954,7803,1922,...,2953,948,1094199,6280,17404,74519,127518,127425,139839,82409
4,PIN2,5LVBQ,100,500,499,16871,15164,27808,6788,1693,...,2899,756,975767,6264,16342,68109,112813,112727,123971,72998

In [ ]:
df_max = df_pin[df_pin["input"] == "PIN5="]
df_max = df_max.drop("DIV", axis=1)
df_max

,input,fila,n,m,c,CMP,TEST,JZ,JNZ,JL,...,SHR,SAR,MOV,MOVZX,MOVSXD,LEA,CALL_NEAR,RET_NEAR,PUSH,POP
42,PIN5,1LVBQ,100000,500000,499999,21159704,25794754,40529334,7615505,3149793,...,4183430,7039828,1264674709,14960570,7699696,99843771,147909067,147713353,162732330,103481993
43,PIN5,2LVBQ,100000,500000,499999,20779247,23152265,42331453,6128848,3349034,...,3966891,4610418,1294509847,14585485,5790680,105426973,151760463,151749211,165772846,103395623
44,PIN5,3LVBQ,100000,500000,499999,20163465,21950544,40379275,5841557,3548565,...,3952700,4556975,1273482553,14570061,10949178,101132030,147790793,147788426,161238746,101291106
45,PIN5,4LVBQ,100000,500000,499999,20980179,22153157,41922014,6071854,3564825,...,3951616,4552679,1324014844,14568699,14357386,104363174,152239425,152238020,166092380,103774985
46,PIN5,5LVBQ,100000,500000,499999,21792096,22384539,43337887,6449257,3585138,...,3951139,4550663,1373675284,14568134,17437591,107654792,156393483,156392572,170628188,105998901
47,PIN5,6LVBQ,100000,500000,499999,22190299,22385484,43537790,6448879,3784078,...,3951141,4550663,1376876083,14568134,17834870,107655434,156394451,156393542,170629307,105999345
48,PIN5,1LVBQDK,100000,500000,499999,18596945,21671186,36123379,6477068,3149793,...,3950158,4546751,1153986477,14567048,8046411,96493763,132371793,132371775,144487246,92896736
49,PIN5,2LVBQDK,100000,500000,499999,19206586,21298281,37215428,4529604,3250066,...,3950158,4546751,1170836503,14567048,9504701,97781911,132869313,132869295,144984766,93195248
50,PIN5,3LVBQDK,100000,500000,499999,19124773,20918057,36833539,4821657,3548551,...,3950158,4546751,1177501720,14567048,12584251,96252947,132886734,132886716,145004761,93208177
51,PIN5,4LVBQDK,100000,500000,499999,19511037,21016083,37214373,4816756,3564551,...,3950158,4546751,1196721041,14567048,15441682,97378282,133305416,133305398,145421696,93457730
52,PIN5,5LVBQDK,100000,500000,499999,19915335,21126442,37430458,4990173,3583786,...,3950158,4546751,1217279482,14567048,17804853,98511527,133735653,133735635,145851116,93715067
53,PIN5,6LVBQDK,100000,500000,499999,20313273,21126661,37629858,4989073,3782726,...,3950158,4546751,1220057103,14567048,18199113,98509951,133735423,133735405,145850890,93714935
54,PIN5,BINH,100000,500000,499999,30107072,27195089,42582775,5057986,6280062,...,5082726,5679324,1594971019,14567049,5790680,132020723,172232367,172232348,185243177,130175942
55,PIN5,FIBH,100000,500000,499999,29748091,34043925,41840097,15811481,6749721,...,3950158,4546751,1405176336,14605220,21967497,97809843,135438446,135438428,147156229,95885875

In [167]:
cols = df_max.columns.drop(["input","n","m","c"])
df_max = df_max[cols]
df_max = df_max.groupby("fila").first()
df_max

,CMP,TEST,JZ,JNZ,JL,JNL,JLE,JNB,JB,JBE,...,SHR,SAR,MOV,MOVZX,MOVSXD,LEA,CALL_NEAR,RET_NEAR,PUSH,POP
fila,,,,,,,,,,,,,,,,,,,,,
1LVBQ,21159704,25794754,40529334,7615505,3149793,39941,700821,4398952,393589,196783,...,4183430,7039828,1264674709,14960570,7699696,99843771,147909067,147713353,162732330,103481993
1LVBQDK,18596945,21671186,36123379,6477068,3149793,39941,700799,3611886,45,22,...,3950158,4546751,1153986477,14567048,8046411,96493763,132371793,132371775,144487246,92896736
2LVBQ,20779247,23152265,42331453,6128848,3349034,39941,700840,4906991,219375,10000,...,3966891,4610418,1294509847,14585485,5790680,105426973,151760463,151749211,165772846,103395623
2LVBQDK,19206586,21298281,37215428,4529604,3250066,39941,700799,4603266,100543,22,...,3950158,4546751,1170836503,14567048,9504701,97781911,132869313,132869295,144984766,93195248
3LVBQ,20163465,21950544,40379275,5841557,3548565,235307,700948,3840557,402128,1726,...,3952700,4556975,1273482553,14570061,10949178,101132030,147790793,147788426,161238746,101291106
3LVBQDK,19124773,20918057,36833539,4821657,3548551,136316,700915,3733640,200453,22,...,3950158,4546751,1177501720,14567048,12584251,96252947,132886734,132886716,145004761,93208177
4LVBQ,20980179,22153157,41922014,6071854,3564825,421527,701803,3845408,400957,1010,...,3951616,4552679,1324014844,14568699,14357386,104363174,152239425,152238020,166092380,103774985
4LVBQDK,19511037,21016083,37214373,4816756,3564551,224577,701643,3737472,200943,22,...,3950158,4546751,1196721041,14567048,15441682,97378282,133305416,133305398,145421696,93457730
5LVBQ,21792096,22384539,43337887,6449257,3585138,605724,704464,3863257,402431,674,...,3951139,4550663,1373675284,14568134,17437591,107654792,156393483,156392572,170628188,105998901
5LVBQDK,19915335,21126442,37430458,4990173,3583786,312698,703756,3749966,202769,22,...,3950158,4546751,1217279482,14567048,17804853,98511527,133735653,133735635,145851116,93715067
6LVBQ,22190299,22385484,43537790,6448879,3784078,605680,704512,3864090,402483,674,...,3951141,4550663,1376876083,14568134,17834870,107655434,156394451,156393542,170629307,105999345
6LVBQDK,20313273,21126661,37629858,4989073,3782726,312646,703804,3750793,202817,22,...,3950158,4546751,1220057103,14567048,18199113,98509951,133735423,133735405,145850890,93714935
BINH,30107072,27195089,42582775,5057986,6280062,2971375,1133070,6975533,47,23,...,5082726,5679324,1594971019,14567049,5790680,132020723,172232367,172232348,185243177,130175942
FIBH,29748091,34043925,41840097,15811481,6749721,437610,700799,7391704,98880,22,...,3950158,4546751,1405176336,14605220,21967497,97809843,135438446,135438428,147156229,95885875

In [168]:
groups = {
    "cmp_test":      ["CMP", "TEST"],
    "jump_cond":     ["JZ", "JNZ", "JL", "JNL", "JLE", "JNB", "JB", "JBE"],
    "mov_cond":      ["CMOVNZ", "SETZ", "SETNZ"],
    "arithmetic":    ["ADD", "SUB", "NEG"],
    "bitwise":       ["XOR", "AND", "OR"],
    "shift":         ["SHL", "SHR", "SAR"],
    "data_transfer": ["MOV", "MOVZX", "MOVSXD", "LEA"],
    "flow_ctrl":     ["CALL_NEAR", "RET_NEAR"],
    "stack":         ["PUSH", "POP"],
}

df_grouped = pd.DataFrame({
    name: df_max[opcodes].sum(axis=1)
    for name, opcodes in groups.items()
})

df_grouped["total"] = df_grouped.sum(axis=1)

df_grouped.index = df_max.index
df_grouped

,cmp_test,jump_cond,mov_cond,arithmetic,bitwise,shift,data_transfer,flow_ctrl,stack,total
fila,,,,,,,,,,
1LVBQ,46954458,57024718,7955489,142576645,33090691,34250416,1387178746,295622420,266214323,2270867906
1LVBQDK,40268131,50102933,6150621,128096678,29650992,32911623,1273093699,264743568,237383982,2062402227
2LVBQ,43931512,57686482,7328218,144062688,34440539,31557249,1420312985,303509674,269168469,2311997816
2LVBQDK,40504867,50439669,6150621,131460842,28981576,34594799,1292690163,265738608,238180014,2088741159
3LVBQ,42114009,54950063,6664730,151036391,33600119,37006007,1400133822,295579219,262529852,2283614212
3LVBQDK,40042830,49975093,6052338,139926845,29181505,38327554,1300905966,265773450,238212938,2108398519
4LVBQ,43133336,56929398,6864054,160389875,34960177,40252519,1457304103,304477445,269867365,2374178272
4LVBQDK,40527120,50460337,6051151,144487805,29099328,41101560,1324108053,266610814,238879426,2141325594
5LVBQ,44176635,58948832,7076426,170107764,36531579,43539826,1513335801,312786055,276627089,2463130007
5LVBQDK,41041777,50973628,6050620,149637685,29191141,43915861,1348162910,267471288,239566183,2176011093
6LVBQ,44575783,59348186,7076613,171306597,36729788,43939182,1516934521,312787993,276628652,2469327315
6LVBQDK,41439934,51371739,6050620,150829625,29389364,44312646,1351333215,267470828,239565825,2181763796
BINH,57302161,65000871,6249458,167388222,29576258,56701785,1747349471,344464715,315419119,2789452060
FIBH,63792016,73030314,6349455,141675484,28422571,44768447,1539558896,270876874,243042104,2411516161

In [169]:
mins = df_grouped.min()
mins
df_norm = df_grouped / mins
df_norm

,cmp_test,jump_cond,mov_cond,arithmetic,bitwise,shift,data_transfer,flow_ctrl,stack,total
fila,,,,,,,,,,
1LVBQ,1.172606,1.141063,1.314822,1.113039,1.164240,1.085342,1.089612,1.116637,1.121450,1.101079
1LVBQDK,1.005627,1.002558,1.016527,1.000000,1.043220,1.042918,1.000000,1.000000,1.000000,1.000000
2LVBQ,1.097113,1.154305,1.211152,1.124640,1.211732,1.000000,1.115639,1.146429,1.133895,1.121022
2LVBQDK,1.011539,1.009296,1.016527,1.026263,1.019668,1.096255,1.015393,1.003759,1.003353,1.012771
3LVBQ,1.051724,1.099549,1.101495,1.179081,1.182163,1.172663,1.099789,1.116474,1.105929,1.107259
3LVBQDK,1.000000,1.000000,1.000284,1.092353,1.026702,1.214540,1.021846,1.003890,1.003492,1.022302
4LVBQ,1.077180,1.139155,1.134438,1.252100,1.230015,1.275540,1.144695,1.150084,1.136839,1.151171
4LVBQDK,1.012094,1.009710,1.000088,1.127959,1.023811,1.302444,1.040071,1.007053,1.006300,1.038268
5LVBQ,1.103235,1.179564,1.169537,1.327964,1.285302,1.379709,1.188707,1.181468,1.165315,1.194301
5LVBQDK,1.024947,1.019981,1.000000,1.168162,1.027041,1.391625,1.058966,1.010303,1.009193,1.055086
6LVBQ,1.113203,1.187555,1.169568,1.337323,1.292275,1.392364,1.191534,1.181475,1.165321,1.197306
6LVBQDK,1.034890,1.027947,1.000000,1.177467,1.034015,1.404199,1.061456,1.010302,1.009191,1.057875
BINH,1.431022,1.300665,1.032862,1.306734,1.040591,1.796791,1.372522,1.301126,1.328730,1.352526
FIBH,1.593095,1.461334,1.049389,1.106004,1.000000,1.418642,1.209305,1.023167,1.023835,1.169275

In [170]:
df_norm.style.highlight_min(axis=0, color="lightgreen").highlight_max(axis=0, color="salmon")

In [171]:
latex = df_norm.to_latex(
    index=True,
    float_format="%.2f",
    longtable=False,
    escape=False
)

print(latex)

\begin{tabular}{lrrrrrrrrrr}
\toprule
 & cmp_test & jump_cond & mov_cond & arithmetic & bitwise & shift & data_transfer & flow_ctrl & stack & total \\
fila &  &  &  &  &  &  &  &  &  &  \\
\midrule
1LVBQ & 1.17 & 1.14 & 1.31 & 1.11 & 1.16 & 1.09 & 1.09 & 1.12 & 1.12 & 1.10 \\
1LVBQDK & 1.01 & 1.00 & 1.02 & 1.00 & 1.04 & 1.04 & 1.00 & 1.00 & 1.00 & 1.00 \\
2LVBQ & 1.10 & 1.15 & 1.21 & 1.12 & 1.21 & 1.00 & 1.12 & 1.15 & 1.13 & 1.12 \\
2LVBQDK & 1.01 & 1.01 & 1.02 & 1.03 & 1.02 & 1.10 & 1.02 & 1.00 & 1.00 & 1.01 \\
3LVBQ & 1.05 & 1.10 & 1.10 & 1.18 & 1.18 & 1.17 & 1.10 & 1.12 & 1.11 & 1.11 \\
3LVBQDK & 1.00 & 1.00 & 1.00 & 1.09 & 1.03 & 1.21 & 1.02 & 1.00 & 1.00 & 1.02 \\
4LVBQ & 1.08 & 1.14 & 1.13 & 1.25 & 1.23 & 1.28 & 1.14 & 1.15 & 1.14 & 1.15 \\
4LVBQDK & 1.01 & 1.01 & 1.00 & 1.13 & 1.02 & 1.30 & 1.04 & 1.01 & 1.01 & 1.04 \\
5LVBQ & 1.10 & 1.18 & 1.17 & 1.33 & 1.29 & 1.38 & 1.19 & 1.18 & 1.17 & 1.19 \\
5LVBQDK & 1.02 & 1.02 & 1.00 & 1.17 & 1.03 & 1.39 & 1.06 & 1.01 & 1.01 & 1.06 \\
6LVBQ & 1.11 & 1.19 & 1.17 & 1.34 & 1.29 & 1.39 & 1.19 & 1.18 & 1.17 & 1.20 \\
6LVBQDK & 1.03 & 1.03 & 1.00 & 1.18 & 1.03 & 1.40 & 1.06 & 1.01 & 1.01 & 1.06 \\
BINH & 1.43 & 1.30 & 1.03 & 1.31 & 1.04 & 1.80 & 1.37 & 1.30 & 1.33 & 1.35 \\
FIBH & 1.59 & 1.46 & 1.05 & 1.11 & 1.00 & 1.42 & 1.21 & 1.02 & 1.02 & 1.17 \\
\bottomrule
\end{tabular}